# Generated by Django 4.2.5 on 2025-05-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('code_barre', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fam', models.CharField(max_length=100)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='gestiondata.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_Menu', models.CharField(max_length=100)),
                ('list_Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_url', models.CharField(max_length=100)),
                ('four_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='gestiondata.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Sfamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sfam', models.CharField(max_length=100)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('id_Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.articles')),
                ('id_Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='gestiondata.url'),
        ),
        migrations.AddField(
            model_name='menu',
            name='articles',
            field=models.ManyToManyField(through='gestiondata.Menu_Article', to='gestiondata.articles'),
        ),
        migrations.AddField(
            model_name='menu',
            name='type_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.typemenu'),
        ),
        migrations.CreateModel(
            name='Fr_Dom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.domain')),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondata.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='gestiondata.categorie'),
        ),
    ]
