# Generated by Django 4.2.5 on 2025-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondata', '0002_articles_categorie_domain_famille_menu_typemenu_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
