# Generated by Django 4.2.5 on 2025-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondata', '0003_menu_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='list_Price',
        ),
    ]
