# Generated by Django 4.2.5 on 2025-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type', models.IntegerField()),
                ('domaine', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('art', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('nif', models.CharField(max_length=20)),
            ],
        ),
    ]
