# Generated by Django 4.2.5 on 2025-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmainpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
